# Generated by Django 4.0.3 on 2022-03-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_name_product_brand_name_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'ประเภทสินค้า', 'verbose_name_plural': 'หมวดหมู่ประเภทสินค้า'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'สินค้า', 'verbose_name_plural': 'ข้อมูลสินค้า'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='new_product',
        ),
    ]
