# Generated by Django 4.0.3 on 2022-03-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='relative_image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
