# Generated by Django 4.0.3 on 2022-03-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_card_table_alter_carditem_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
