# Generated by Django 4.0.3 on 2022-04-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_profileuser_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
