# Generated by Django 4.0.3 on 2022-04-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_order_tel_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
