# Generated by Django 4.0.3 on 2022-04-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_order_tel_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tel',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
