# Generated by Django 4.0.3 on 2022-04-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tel',
            field=models.CharField(max_length=10),
        ),
    ]
