# Generated by Django 4.0.3 on 2022-04-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.TimeField(),
        ),
    ]
