# Generated by Django 4.0.3 on 2022-04-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_alter_payment_date_alter_payment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
