# Generated by Django 4.0.3 on 2022-04-10 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_alter_payment_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
