# Generated by Django 4.0.3 on 2022-04-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_rename_username_payment_order_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
