# Generated by Django 4.0.3 on 2022-04-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
