# Generated by Django 4.0.3 on 2022-04-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_alter_payment_order_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='item',
        ),
    ]
