# Generated by Django 4.0.3 on 2022-04-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_rename_payment_userpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='method',
            field=models.CharField(choices=[('KTB 984-5-70890-0 ', 'KTB'), ('K-BANK 114-3-423-324', 'K-BANK')], max_length=50),
        ),
    ]
