# Generated by Django 4.0.3 on 2022-04-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_alter_userpayment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='method',
            field=models.CharField(choices=[('KTB', 'KTB 984-5-70890-0'), ('K-BANK', 'K-BANK 984-5-70890-0')], max_length=50),
        ),
    ]
